# Generated by Django 2.1.15 on 2020-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('subid', models.CharField(db_column='SUBID', max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='Type', max_length=20)),
                ('text1', models.CharField(blank=True, db_column='Text1', max_length=1000, null=True)),
                ('text2', models.CharField(blank=True, db_column='Text2', max_length=1000, null=True)),
                ('text3', models.CharField(blank=True, db_column='Text3', max_length=40, null=True)),
                ('subct', models.CharField(blank=True, db_column='SUBCT', max_length=10, null=True)),
            ],
            options={
                'db_table': '[dbo].[product_list]',
                'managed': False,
            },
        ),
    ]
